name: walls
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  image_gallery_saver: ^1.2.2
  permission_handler: ^5.0.0+hotfix.5
  random_string: ^2.0.1
  cached_network_image: ^2.2.0+1
  dio: ^3.0.9
  flutter_launcher_icons: ^0.7.2
  firebase_storage: ^3.1.5
  firebase_core: ^0.4.4+3
  firebase_database: ^3.1.5
  fluttertoast: ^4.0.1
  curved_navigation_bar: ^0.3.2
  bottom_navy_bar: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android : "launcher_icon"
  ios : "true"
  image_path : "assests/icon.png"

flutter_launcher_name :
  name : "WallsHub"



